// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnypgorcixeupgzkdpvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJueXBnb3JjaXhldXBnemtkcHZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDM2NDAsImV4cCI6MjA2ODg3OTY0MH0.ZPeVPdwsPj78ivXunUmKPNKqLKBKC9Wyofi_fEgOH9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});